travis:
  secure:
    BINSTAR_TOKEN: PCvdwTfRlqJmanYcsHHJblFNxw35/UYspxgRE8fTOXjOhdtDEY/ItwlQhl8Qbf6dVV/7bL9gyOxvqLZeSh5ks8FRReOyYtCeardoiTrqlZEXoGctA60q+RZ1icdNLM4xtod2fwikVq9xg95c1bZvclFCjCPIKANo3d55pDZN+FekTCUm0fvPv0flbND5s2leq0hkbDYlj7RB7uh3LYz2+8zen7QL943M7wRBhh9MUokPQa4XyfPiZLu94b/mBA4i9g3RVl6jrOAPXnMkU5X555dpTgc84z7PtouN57lLGJZLyPEkclc3YaojYTHtdk9QxhrlMJxccd72OKcfvAEGW1tDfzztEOpEVX7Alc3ujxYj1PLfPjTaloUwfk3ixfG9TQM8lJ9pozg7FgWxPZvesESRnrAL6COPEgSiqQhuB6rrkkrLZyw0DRWyHtyvuqjFsIwZdryYzNI3zXAwlqAhtNPqKGQ5pSX0n7jIZBZ74Va5F80hQqQyq/EBqYUCt6VLWWKNsk3ezgbw9UNqNTI9Eo6bP1OUZG+hTPi27nCX2qfVlpTbxuXXNz0gqHChFIz0AF8W7pIYPMKCBYdWs5JMmBbV5RHP7KQotJ120rgFT5dGVZEzf4oJEiOAauOegezZuWZQyFQ3EQaiWhJ/qYGWXx4XI+XB9g+LauoKQ9rcI90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
